#!/usr/bin/env python

from imagededup.methods import PHash
import os
import argparse
import json
from pathlib import Path
from flask import Flask, render_template, request
import webbrowser
from threading import Timer

import warnings
warnings.filterwarnings('ignore')

def open_browser():
      webbrowser.open_new("http://localhost:5001")

def group_images(image_pairs, path=None):
    grouped = {}
    result = []
    for _img, connections in list(image_pairs.items()):
        if len(connections) > 0:
            img = _img if path == None else f'{path}/{_img}'
            if img in grouped:
                continue
            new_group = [img]
            grouped[img] = True
            for _conn_img, weight in connections:
                conn_img = _conn_img if path == None else f'{path}/{_conn_img}'
                if conn_img not in grouped:
                    new_group.append(conn_img)
                    grouped[conn_img] = True
            if len(new_group) > 1:
                result.append((new_group, weight))
    return sorted(result, key=lambda x: x[1], reverse=False)

def main(args):
    if not args['images'].exists():
        print(f"folder '{args['images']}' does not exist")
        return

    image_folder = args['images']
    duplicates_folder = Path(f'{image_folder.name}_duplicates')
    if not duplicates_folder.exists():
        duplicates_folder.mkdir()

    phasher = PHash()
    duplicates = group_images(phasher.find_duplicates(image_dir=image_folder.name, recursive=True, scores=True, max_distance_threshold=args['threshold']), image_folder.name)

    if len(duplicates) > 0:
        app = Flask(__name__, template_folder='.', static_url_path='', static_folder='.')

        @app.route('/')
        def index_page():
            return render_template('./find-image-duplicates.html', duplicates=duplicates)

        @app.route('/move', methods=['POST'])
        def move_image():
            request_data = request.get_json()
            p = Path(request_data['path'])
            target_folder = duplicates_folder.name if list(p.parents)[-2].name == image_folder.name else image_folder.name
            target = Path(target_folder).joinpath(*p.parts[1:])
            Path(target).parents[0].mkdir(parents=True, exist_ok=True)
            p.rename(target)
            return {'path': str(target)}

        Timer(1, open_browser).start()
        app.run('localhost', '5001')
    else:
        print('\n no duplicates found')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Manage Image Duplicates', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--images', default='./todo_photos', metavar='PATH', type=Path, help='image folder')
    parser.add_argument('--threshold', default=10, type=int, metavar='N', help='max distance threshold')
    main(vars(parser.parse_args()))
