#!/usr/bin/env bash

#
# Photo Tools
#
# USAGE
#
#     photo-tools --types FOLDER              # list filetypes
#     photo-tools --normalize FOLDER          # slugify filenames, set propper file permissions
#     photo-tools --group FOLDER              # group images into 'photos' and movies into 'movies' folder
#
# COMMANDS
#
#     fd -e jpg . todo -x mv {} photos/       # mode jpg files into 'photos' folder
#     fd -e mov . todo -x mv {} movies/       # mode mpv files into 'movies' folder
#

show_help() {
  awk '/^[^ #]/{c=1}c==0{print $0}' $0 | sed -n '/^#/p' | sed 1d | sed 's/^#/ /g' \
    | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/(USAGE|EXAMPLES|COMMANDS)/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/\`(.+)\`/$(tput sgr 0 1)\1$(tput sgr 0)/"
  exit 1
}

filetypes() {
  [ ! -d "$1" ] && show_help
  while read -r file
  do
    echo "${file##*.}"
  done < <(fd . -t f "$1") \
  | sort \
  | uniq -c
}

normalize() {
  [ ! -d "$1" ] && show_help
  # FIXME convert -> magick
  fd . -e heic "$1" -x convert {} {.}.jpg
  fd . -e heic "$1" -X rm
  fd . -e jpeg "$1" -x mv {} {.}.jpg
  while read -r file
  do
    slugify -adx "$file"
    chmod 644 "$file"
    xattr -d com.apple.quarantine "$file"
  done < <(fd . -t f "$1")
}

group() {
  [ ! -d "$1" ] && show_help
  mkdir -p photos
  fd . -e jpg -e jpeg -e png -e gif -e heic "$1" -x mv {} photos/
  mkdir -p movies
  fd . -e mov -e mp4 "$1" -x mv {} movies/
}

[[ -z "$1" ]] && show_help

while [ $# -gt 0 ]; do
  case $1 in
    -t|--types)
      shift
      filetypes "$1"
      ;;
    -n|--normalize)
      shift
      normalize "$1"
      ;;
    -g|--group)
      shift
      group "$1"
      ;;
    -h|--help)
      show_help
      ;;
    *)
      ;;
  esac
  shift
done

exit 0
