#!/usr/bin/env bash

_phototools_completions() {
    local cur prev alias
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMPREPLY=($(compgen -W "--help --clean --types --normalize --group --aec --exif --duplicates --distribute $(fd -I -t d -d 1)" -- ${cur}))
}

complete -F _phototools_completions photo-tools

