#!/usr/bin/env bash

_phototools_completions() {
    local cur prev alias
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMPREPLY=($(compgen -W "--types --normalize --group --aec --exif --duplicates --distribute" -- ${cur}))
}

complete -F _phototools_completions photo-tools

